apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-fetcher
          image: engjuanser/image-fetcher:2.6
          resources:
            requests:
              memory: "8Mi"
              cpu: "5m"
            limits:
              memory: "16Mi"
              cpu: "25m"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: todo-project-config
        - name: todo-frontend
          image: PROJECT/FRONTEND
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          envFrom:
            - configMapRef:
                name: todo-project-config
