apiVersion: v1
kind: Service
metadata:
  name: wikipedia-init-sidecar-svc
  namespace: default
  labels:
    app: wikipedia-init-sidecar
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wikipedia-init-sidecar
  type: ClusterIP
