apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - manifests/configmap.yaml
  - manifests/secret.yaml
  - manifests/secret-broadcaster.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/statefulset-postgres.yaml
  - manifests/deployment-backend.yaml
  - manifests/deployment-frontend.yaml
  - manifests/deployment-broadcaster.yaml
  - manifests/service-backend.yaml
  - manifests/service-frontend.yaml
  - manifests/ingress.yaml

images:
  - name: PROJECT/FRONTEND
    newName: engjuanser/todo-frontend
    newTag: "4.5"
  - name: PROJECT/BACKEND
    newName: engjuanser/todo-backend
    newTag: "4.6"
