apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: todo-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "prod-postgres-svc"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "nats://my-nats.project.svc.cluster.local:4222"
  - target:
      kind: Deployment
      name: todo-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: todo-broadcaster
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "nats://my-nats.project.svc.cluster.local:4222"

images:
  - name: PROJECT/FRONTEND
    newName: engjuanser/todo-frontend
    newTag: "4.5"
  - name: PROJECT/BACKEND
    newName: engjuanser/todo-backend
    newTag: "4.6"
  - name: PROJECT/BROADCASTER
    newName: engjuanser/todo-broadcaster
    newTag: "4.6"
