apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: todo-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: todo-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: PROJECT/FRONTEND
    newName: engjuanser/todo-frontend
    newTag: "4.5"
  - name: PROJECT/BACKEND
    newName: engjuanser/todo-backend
    newTag: "4.6"
  - name: PROJECT/BROADCASTER
    newName: engjuanser/todo-broadcaster
    newTag: "4.6"
