apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

namePrefix: staging-

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-broadcaster
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: NATS_URL
            value: "nats://my-nats:4222"
          - name: WEBHOOK_URL
            value: ""
          - name: WEBHOOK_TYPE
            value: "generic"

images:
  - name: PROJECT/FRONTEND
    newName: engjuanser/todo-frontend
    newTag: "4.5"
  - name: PROJECT/BACKEND
    newName: engjuanser/todo-backend
    newTag: "4.6"
  - name: PROJECT/BROADCASTER
    newName: engjuanser/todo-broadcaster
    newTag: "4.6"
